networks:
  factures:

services:

    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx.Dockerfile
        depends_on:
            - php
            - sqlite
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html
        networks:
            - factures

    php:
        build:
            context: .
            dockerfile: ./docker/php.Dockerfile
        container_name: php
        user: "1000:1000"
        ports:
            - "9000:9000"
        volumes:
            - ./src:/var/www/html
            - ./sqlite:/var/www/html/sqlite
        depends_on:
            - sqlite
        networks:
            - factures

    sqlite:
        image: nouchka/sqlite3:latest
        stdin_open: true
        tty: true
        networks:
            - factures
        volumes:
            - ./sqlite:/root/db/


    composer:
        build:
            context: .
            dockerfile: ./docker/php.Dockerfile
        container_name: laravel_composer
        user: "1000:1000"
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['composer']
        networks:
            - factures

    artisan:
        build:
            context: .
            dockerfile: ./docker/php.Dockerfile
        container_name: laravel_artisan
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['php', 'artisan']
        networks:
            - factures

    npm:
        image: node:current-alpine
        container_name: npm
        ports:
            - "5173:5173"
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']






        